openapi: 3.0.0
info:
  version: '1.0.0'
  title: Watcher security-critical API
  description: >
    API specification of the Watcher's security-critical Service
    
    Error codes are available in [html](https://github.com/omisego/elixir-omg/blob/master/docs/api_specs/errors.md#error-codes-description) format.
  contact:
    name: OmiseGO
    email: omisego@omisego.co
  license:
    name: 'Apache 2.0: https://www.apache.org/licenses/LICENSE-2.0'
    url: 'https://omisego.network/'

tags:
  - name: Status
    description: Status of the child chain.
    externalDocs:
      description: "Byzantine events description"
      url: "https://github.com/omisego/elixir-omg/blob/master/docs/api_specs/status_events_specs.md#byzantine-events"
  - name: UTXO
    description: UTXO related API.
  - name: Transaction
    description: Transaction related API.
  - name: InFlightExit
    description: InFlightExit related API.    

paths:
  /status.get:
    post:
      tags:
        - Status
      summary: Returns information about the current state of the child chain and the watcher.
      description: >
        The most critical function of the Watcher is to monitor the ChildChain and report dishonest activity.
        The user must call the `/status.get` endpoint periodically to check. Any situation that requires the user 
        to either exit or challenge an invalid exit will be included in the `byzantine_events` field.
      operationId: status
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        200:
          $ref: '#/responses/StatusOpId'
        500:
          $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/InternalServerError'
  /utxo.get_utxos:
    post:
      tags:
        - UTXO
      summary: Gets all utxos belonging to the given address.
      description: >
        Note that this is a performance intensive call and should only be used if the chain is byzantine and the user needs to retrieve utxo information to be able to exit.
        Normally an application should use the Informational API's [Account - Get Utxos](http://TODO) instead.
        This version is provided in case the Informational API is not available.
      operationId: getUtxos
      consumes:
      - application/json
      produces:
      - application/json
      requestBody:
        $ref: 'requests.yaml#/AddressBodySchema'
      responses:
        200:
          $ref: '#/responses/GetUtxosOpId'
        500:
          $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/InternalServerError'
  /utxo.get_challenge_data:
    post:
      tags:
        - UTXO
      summary: Gets challenge data for a given utxo exit.
      description:
      operationId: getUtxoChallenge
      consumes:
      - application/json
      produces:
      - application/json
      requestBody:
        $ref: 'requests.yaml#/UtxoPosBodySchema'
      responses:
        200:
          $ref: '#/responses/GetUtxoChallengeOpId'
        500:
          $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/InternalServerError'
  /utxo.get_exit_data:
    post:
      tags:
        - UTXO
      summary: Gets exit data for a given utxo.
      description:
      operationId: getUtxoExit
      consumes:
      - application/json
      produces:
      - application/json
      requestBody:
        $ref: 'requests.yaml#/UtxoPosBodySchema'
      responses:
        200:
          $ref: '#/responses/GetUtxoExitOpId'
        500:
          $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/InternalServerError'
  /transaction.submit:
    post:
      tags:
        - Transaction
      summary: Sends transaction to Child chain.
      description: Watcher passes signed transaction to the child chain only if it's secure, e.g. Watcher is fully synced, all operator blocks have been verified, transaction doesn't spend funds not yet mined...
      operationId: submit
      consumes:
      - application/json
      produces:
      - application/json
      requestBody:
        $ref: 'requests.yaml#/TransactionBodySchema'
      responses:
        200:
          $ref: '#/responses/SubmitOpId'
        500:
          $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/InternalServerError'
  /in_flight_exit.get_data:
    post:
      tags:
        - InFlightExit
      summary: Gets exit data for an in-flight exit. 
      description: Exit data are arguments to `startInFlightExit` root chain contract function.
      operationId: getInFlightExit
      consumes:
      - application/json
      produces:
      - application/json
      requestBody:
        $ref: 'requests.yaml#/TransactionBodySchema'
      responses:
        200:
          $ref: '#/responses/GetInFlightExitOpId'
        500:
          $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/InternalServerError'          
  /in_flight_exit.get_competitor:
    post:
      tags:
        - InFlightExit
      summary: Returns a competitor to an in-flight exit.
      description: Note that if the competing transaction has not been put into a block `competing_tx_pos` and `competing_proof` will not be returned.
      operationId: getCompetitor
      consumes:
      - application/json
      produces:
      - application/json
      requestBody:
        $ref: 'requests.yaml#/TransactionBodySchema'
      responses:
        200:
          $ref: '#/responses/GetCompetitorOpId'
        500:
          $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/InternalServerError'
  /in_flight_exit.prove_canonical:
    post:
      tags:
        - InFlightExit
      summary: Proves transaction is canonical. 
      description: To respond to a challenge to an in-flight exit, this proves that the transaction has been put into a block (and therefore is canonical).
      operationId: proveCanonical
      consumes:
      - application/json
      produces:
      - application/json
      requestBody:
        $ref: 'requests.yaml#/TransactionBodySchema'
      responses:
        200:
          $ref: '#/responses/ProveCanonicalOpId'
        500:
          $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/InternalServerError'
  /in_flight_exit.get_input_challenge_data:
    post:
      tags:
        - InFlightExit
      summary: Gets the data to challenge an invalid input piggybacked on an in-flight exit. 
      description: 
      operationId: getInputChallengeData
      consumes:
      - application/json
      produces:
      - application/json
      requestBody:
        $ref: '#/requests/GetInputChallengeDataOpId'
      responses:
        200:
          $ref: '#/responses/GetInputChallengeDataOpId'
        500:
          $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/InternalServerError'    
  /in_flight_exit.get_output_challenge_data:
    post:
      tags:
        - InFlightExit
      summary: Gets the data to challenge an invalid output piggybacked on an in-flight exit. 
      description: 
      operationId: getOutputChallengeData
      consumes:
      - application/json
      produces:
      - application/json
      requestBody:
        $ref: '#/requests/GetOutputChallengeDataOpId'
      responses:
        200:
          $ref: '#/responses/GetOutputChallengeDataOpId'
        500:
          $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/InternalServerError'

requests:
  GetInputChallengeDataOpId:
    description: In-flight transaction bytes and invalid input index
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            txbytes:
              type: string
              format: binary
            input_index:
              type: integer
              format: int8
          example:
            txbytes: '0xf3170101c0940000...'
            input_index: 1
  GetOutputChallengeDataOpId:
    description: In-flight transaction bytes and invalid output index
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            txbytes:
              type: string
              format: binary
            output_index:
              type: integer
              format: int8
          example:
            txbytes: '0xf3170101c0940000...'
            output_index: 0

responses:
  GetUtxosOpId: 
    description: Account utxos successful response
    content:
      application/json:
        schema:
          allOf:
          - $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/BaseResponseSchema'
          - type: object
            properties:
              data:
                type: array
                items:
                - $ref: 'schemata.yaml#/TransactionOutputSchema'
            example:
              data:
              - 
                blknum: 123000
                txindex: 111
                oindex: 0
                utxo_pos: 123000001110000
                owner: '0xb3256026863eb6ae5b06fa396ab09069784ea8ea'
                currency: '0x0000000000000000000000000000000000000000'
                amount: 10
  GetUtxoChallengeOpId:
    description: Utxo challenge successful response
    content:
      application/json:
        schema:
          allOf:
          - $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/BaseResponseSchema'
          - type: object
            properties:
              data:
                type: object
                properties:
                  input_index:
                    type: integer
                    format: int8
                  utxo_pos:
                    type: integer
                    format: int256                
                  sig:
                    type: string
                    format: binary
                  txbytes:
                    type: string
                    format: binary
            example:
              data:
                input_index: 0
                utxo_pos: 3000000000000
                sig: '0x6bfb9b2dbe32...'
                txbytes: '0x3eb6ae5b06f3...'
  GetUtxoExitOpId:
    description: Utxo challenge successful response
    content:
      application/json:
        schema:
          allOf:
          - $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/BaseResponseSchema'
          - type: object
            properties:
              data:
                type: object
                properties:
                  utxo_pos:
                    type: integer
                    format: int256                
                  txbytes:
                    type: string
                    format: binary
                  proof:
                    type: string
                    format: binary     
            example:
              data:
                utxo_pos: 10000000010000000
                txbytes: '0x3eb6ae5b06f3'
                proof: '0xcedb8b31d1e4'
  SubmitOpId:
    description: Transaction submission successful response
    content:
      application/json:
        schema:
          allOf:
          - $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/BaseResponseSchema'
          - type: object
            properties:
              data:
                type: object
                properties:
                  blknum:
                    type: integer
                    format: int64
                  txindex:
                    type: integer
                    format: int16
                  txhash:
                    type: string
                    format: binary
            example:
              data:
                blknum: 123000
                txindex: 111
                txhash: '0xbdf562c24ace032176e27621073df58ce1c6f65de3b5932343b70ba03c72132d'
  StatusOpId:
    description: Status successful response
    content:
      application/json:
        schema:
          allOf:
          - $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/BaseResponseSchema'
          - type: object
            properties:
              data:
                type: object
                properties:
                  last_validated_child_block_timestamp:
                    type: integer
                    format: int64
                  last_validated_child_block_number:
                    type: integer
                    format: int64
                  last_mined_child_block_timestamp:
                    type: integer
                    format: int64
                  last_mined_child_block_number:
                    type: integer
                    format: int64
                  last_seen_eth_block_timestamp:
                    type: integer
                    format: int64
                  last_seen_eth_block_number:
                    type: integer
                    format: int64
                  eth_syncing:
                    type: boolean
                  byzantine_events:
                    type: array
                  in_flight_txs:
                    type: array
                  in_flight_exits:
                    type: array
                  contract_addr:
                    type: string
                  services_synced_heights:
                    type: array
            example:
              data:
                last_validated_child_block_number: 10000
                last_mined_child_block_timestamp: 1535031020
                last_mined_child_block_number: 11000
                eth_syncing: true
                byzantine_events:
                -
                  event: invalid_exit
                  details:
                    eth_height: 615440
                    utxo_pos: 10000000010000000
                    owner: '0xb3256026863eb6ae5b06fa396ab09069784ea8ea'
                    currency: '0x0000000000000000000000000000000000000000'
                    amount: 100
                in_flight_txs:
                -
                  txhash: '0xbdf562c24ace032176e27621073df58ce1c6f65de3b5932343b70ba03c72132d'
                  txbytes: '0x3eb6ae5b06f3...'
                  input_addresses:
                  - '0x1234...'
                  ouput_addresses:
                  - '0x1234...'
                  - '0x7890...'
                in_flight_exits:
                -
                  txhash: '0x5df13a6bf96dbcf6e66d8babd6b55bd40d64d4320c3b115364c6588fc18c2a21'
                  txbytes: '0xf3170101c094...'
                  eth_height: 615441
                  piggybacked_inputs: 
                  - 1
                  piggybacked_outputs:
                  - 0
                  - 1
  GetInFlightExitOpId:
    description: Get in-flight exit successful response
    content:
      application/json:
        schema:
          allOf:
          - $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/BaseResponseSchema'
          - type: object
            properties:
              data:
                type: object
                properties:
                  in_flight_tx:
                    type: string
                    format: binary
                  input_txs:
                    type: string
                    format: binary
                  input_txs_inclusion_proofs:
                    type: string
                    format: binary
                  in_flight_tx_sigs:
                    type: string
                    format: binary
            example:
              data:
                in_flight_tx: '0xf3170101c0940000...'
                input_txs: '0xa3470101c0940000...'
                input_txs_inclusion_proofs : '0xcedb8b31d1e4...'
                in_flight_tx_sigs : '0x6bfb9b2dbe32...'
  GetCompetitorOpId:
    description: Get competitor successful response
    content:
      application/json:
        schema:
          allOf:
          - $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/BaseResponseSchema'
          - type: object
            properties:
              data:
                type: object
                properties:
                  in_flight_txbytes:
                    type: string
                    format: binary
                  in_flight_input_index:
                    type: integer
                    format: int8
                  competing_txbytes:
                    type: string
                    format: binary
                  competing_input_index:
                    type: integer
                    format: int8
                  competing_sig:
                    type: string
                    format: binary
                  competing_tx_pos:
                    type: integer
                    format: int256
                  competing_proof:
                    type: string
                    format: binary
            example:
              data:
                in_flight_txbytes: '0xf3170101c0940000...'
                in_flight_input_index: 1
                competing_txbytes: '0x5df13a6bee20000...'
                competing_input_index: 1
                competing_sig: '0xa3470101c0940000...'
                competing_tx_pos: 26000003920000
                competing_proof: '0xcedb8b31d1e4...'
  ProveCanonicalOpId:
    description: Prove canonical successful response
    content:
      application/json:
        schema:
          allOf:
          - $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/BaseResponseSchema'
          - type: object
            properties:
              data:
                type: object
                properties:
                  in_flight_txbytes:
                    type: string
                    format: binary
                  in_flight_tx_pos:
                    type: integer
                    format: int256
                  in_flight_proof:
                    type: string
                    format: binary
            example:
              data:
                in_flight_txbytes: '0xf3170101c0940000...'
                in_flight_tx_pos: 26000003920000
                in_flight_proof: '0xcedb8b31d1e4...'
  GetInputChallengeDataOpId:
    description: Get input challenge successful response
    content:
      application/json:
        schema:
          allOf:
          - $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/BaseResponseSchema'
          - type: object
            properties:
              data:
                type: object
                properties:
                  in_flight_txbytes:
                    type: string
                    format: binary
                  in_flight_input_index:
                    type: integer
                    format: int8
                  spending_txbytes:
                    type: string
                    format: binary
                  spending_input_index:
                    type: integer
                    format: int8
                  spending_sig:
                    type: string
                    format: binary
            example:
              data:
                in_flight_txbytes: '0xf3170101c0940000...'
                in_flight_input_index: 1
                spending_txbytes: '0x5df13a6bee20000...'
                spending_input_index: 1
                spending_sig: '0xa3470101c0940000...'
  GetOutputChallengeDataOpId:
    description: Get output challenge successful response
    content:
      application/json:
        schema:
          allOf:
          - $ref: '../../../omg_rpc/priv/swagger/shared.yaml#/BaseResponseSchema'
          - type: object
            properties:
              data:
                type: object
                properties:
                  in_flight_txbytes:
                    type: string
                    format: binary
                  in_flight_output_pos:
                    type: integer
                    format: int256
                  in_flight_proof:
                    type: string
                    format: binary
                  spending_txbytes:
                    type: string
                    format: binary
                  spending_input_index:
                    type: integer
                    format: int8
                  spending_sig:
                    type: string
                    format: binary
            example:
              data:
                in_flight_txbytes: '0xf3170101c0940000...'
                in_flight_output_pos: 21000634002
                in_flight_proof: '0xcedb8b31d1e4...'
                spending_txbytes: '0x5df13a6bee20000...'
                spending_input_index: 1
                spending_sig: '0xa3470101c0940000...'

definitions:
